#!/usr/bin/env python3
"""Generate Pi specialists from the operator's authoritative Codex role files."""
import argparse
import hashlib
import json
from pathlib import Path
import re
import tomllib

ROLE_NAMES = frozenset('architect branch-reviewer brief-author cleaner code-reviewer e2e-runner fixer fixer-max hardener implementer implementer-max plan-validator scout security-reviewer validator-reality validator-spec-reality validator-structure validator-tests'.split())
READ_ONLY = frozenset('branch-reviewer code-reviewer scout security-reviewer validator-reality validator-spec-reality validator-structure validator-tests'.split())
MARKER = '<!-- Generated by Superpowers install-pi-agents.py. Do not edit. -->'


def render_role(source: Path, contract: Path) -> str:
    role = tomllib.loads(source.read_text())
    name = role['name']
    if name != source.stem or name not in ROLE_NAMES:
        raise ValueError(f'Unexpected role identity: {source}')
    instructions = role['developer_instructions']
    match = re.search(r'<!-- SOURCE_BODY_BEGIN: [^\n]+ -->\n', instructions)
    if not match:
        raise ValueError(f'Missing source contract marker: {source}')
    body = instructions[match.end():]
    if role['sandbox_mode'] not in ('read-only', 'workspace-write'):
        raise ValueError(f'Unsupported sandbox: {source}')
    fields = {
        'name': name,
        'description': role['description'],
        'model': 'openai-codex/' + role['model'],
        'thinking': role['model_reasoning_effort'],
        'advertise': True,
        'systemPromptMode': 'append',
        'inheritProjectContext': True,
        'inheritGlobalContext': True,
        'inheritSkills': True,
        'async': True,
        'subagentOnlyExtensions': str(Path(__file__).resolve().parents[1] / '.pi/extensions/child-global-context.ts'),
        'completionGuard': False,
        'acceptanceRole': 'read-only' if name in READ_ONLY else 'writer',
    }
    if name in READ_ONLY:
        fields['tools'] = 'read, grep, find, ls, bash'
    if name == 'plan-validator':
        fields['allowNestedSubagents'] = True
        fields['maxSubagentDepth'] = 2
    header = '\n'.join(f'{key}: {json.dumps(value)}' for key, value in fields.items())
    delegation = ('Dispatch validator-reality, validator-tests, and validator-structure through Pi subagent with their exact canonical names, agentScope: "user", context: "fresh", async: true. Do not pass model or thinking overrides. Issue three direct async subagent calls without waiting between calls to run the independent checks. workflowScript is blocked because child code can override the verified role scope.' if name == 'plan-validator' else 'Do not delegate. Return the assigned result to the parent.')
    return f'''---
{header}
---
{MARKER}
<!-- Codex source: {source}; SHA-256: {hashlib.sha256(source.read_bytes()).hexdigest()} -->

## Pi harness adaptation

These mechanics replace Claude and Codex harness mechanics in the preserved contract below. The frontmatter model and thinking pins override model-routing prose. Use Pi read/write/edit/bash tools for equivalent permitted actions. Load applicable SKILL.md files with read. Inherit operator and project instructions and the discovered skills catalog.

{delegation}

Read {contract} wherever the contract refers to ~/.claude/agents/implementer-contract.md. Other explicit source paths remain dependencies and must be read at their original locations. Do not silently substitute another role, model, skill or missing dependency.

For read-only work, never edit repository files. Bash is restricted to commands permitted by the source contract. Pi does not provide the Codex OS sandbox, so the role's no-write rule is a behavioral restriction, not filesystem isolation.

<!-- SOURCE_BODY_BEGIN -->
{body}'''


def install(source_dir: Path, destination: Path, check: bool = False) -> None:
    sources = {path.stem: path for path in source_dir.glob('*.toml')}
    if set(sources) != ROLE_NAMES:
        raise ValueError(f'Role set mismatch: missing={ROLE_NAMES - set(sources)}, extra={set(sources) - ROLE_NAMES}')
    contract = source_dir / 'implementer-contract.md'
    if not contract.is_file():
        raise ValueError(f'Missing dependency: {contract}')
    rendered = {destination / f'{name}.md': render_role(sources[name], contract) for name in sorted(ROLE_NAMES)}
    for path, content in rendered.items():
        if path.exists() and MARKER not in path.read_text():
            raise ValueError(f'Refusing to overwrite unmanaged agent: {path}')
        if check and (not path.exists() or path.read_text() != content):
            raise ValueError(f'Generated agent is missing or stale: {path}')
    if check:
        return
    destination.mkdir(parents=True, exist_ok=True)
    for path, content in rendered.items():
        path.write_text(content)


if __name__ == '__main__':
    parser = argparse.ArgumentParser(description=__doc__)
    parser.add_argument('--source', type=Path, default=Path.home() / '.codex/agents')
    parser.add_argument('--destination', type=Path, default=Path.home() / '.pi/agent/agents')
    parser.add_argument('--check', action='store_true')
    arguments = parser.parse_args()
    install(arguments.source.resolve(), arguments.destination.resolve(), arguments.check)
    print(f'{"Verified" if arguments.check else "Installed"} {len(ROLE_NAMES)} Pi roles in {arguments.destination}')
